# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bonree/proto/msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bonree/proto/msg.proto',
  package='com.bonree.one.logs.proto',
  syntax='proto3',
  serialized_options=b'\n\031com.bonree.one.logs.protoP\001Z\036internal/bonree/one/logs/proto\252\002\031com.bonree.one.logs.proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x62onree/proto/msg.proto\x12\x19\x63om.bonree.one.logs.proto\"\xb6\x01\n\x03Msg\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0e\n\x06msgLen\x18\x03 \x01(\r\x12\x13\n\x0b\x65ncryptType\x18\x05 \x01(\r\x12\x14\n\x0c\x63ompressType\x18\x06 \x01(\r\x12\x11\n\ttimeStamp\x18\x07 \x01(\x04\x12\x33\n\x07msgType\x18\x08 \x01(\x0e\x32\".com.bonree.one.logs.proto.MsgType\x12\x0f\n\x07msgBody\x18\t \x01(\x0cJ\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05*F\n\x07MsgType\x12\x14\n\x10MT_CONGIF_UNKNOW\x10\x00\x12\x11\n\rMT_CONGIF_REQ\x10\x01\x12\x12\n\x0eMT_CONFIG_RESP\x10\x02*>\n\x0b\x45ncryptType\x12\x0b\n\x07\x45T_NONE\x10\x00\x12\n\n\x06\x45T_DES\x10\x01\x12\n\n\x06\x45T_AES\x10\x02\x12\n\n\x06\x45T_RSA\x10\x03*8\n\x0c\x43ompressType\x12\x0b\n\x07\x43T_NONE\x10\x00\x12\x0b\n\x07\x43T_GZIP\x10\x01\x12\x0e\n\nCT_DEFLATE\x10\x02*O\n\x0fLOG_MSG_VERSION\x12\x1c\n\x18LOG_PROTO_VERSION_UNKNOW\x10\x00\x12\x1e\n\x19LOG_PROTO_VERSION_CURRENT\x10\x80\x02\x42Y\n\x19\x63om.bonree.one.logs.protoP\x01Z\x1einternal/bonree/one/logs/proto\xaa\x02\x19\x63om.bonree.one.logs.protob\x06proto3'
)

_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='com.bonree.one.logs.proto.MsgType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MT_CONGIF_UNKNOW', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MT_CONGIF_REQ', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MT_CONFIG_RESP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=238,
  serialized_end=308,
)
_sym_db.RegisterEnumDescriptor(_MSGTYPE)

MsgType = enum_type_wrapper.EnumTypeWrapper(_MSGTYPE)
_ENCRYPTTYPE = _descriptor.EnumDescriptor(
  name='EncryptType',
  full_name='com.bonree.one.logs.proto.EncryptType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ET_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ET_DES', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ET_AES', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ET_RSA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=310,
  serialized_end=372,
)
_sym_db.RegisterEnumDescriptor(_ENCRYPTTYPE)

EncryptType = enum_type_wrapper.EnumTypeWrapper(_ENCRYPTTYPE)
_COMPRESSTYPE = _descriptor.EnumDescriptor(
  name='CompressType',
  full_name='com.bonree.one.logs.proto.CompressType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CT_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CT_GZIP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CT_DEFLATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=374,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_COMPRESSTYPE)

CompressType = enum_type_wrapper.EnumTypeWrapper(_COMPRESSTYPE)
_LOG_MSG_VERSION = _descriptor.EnumDescriptor(
  name='LOG_MSG_VERSION',
  full_name='com.bonree.one.logs.proto.LOG_MSG_VERSION',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOG_PROTO_VERSION_UNKNOW', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOG_PROTO_VERSION_CURRENT', index=1, number=256,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=432,
  serialized_end=511,
)
_sym_db.RegisterEnumDescriptor(_LOG_MSG_VERSION)

LOG_MSG_VERSION = enum_type_wrapper.EnumTypeWrapper(_LOG_MSG_VERSION)
MT_CONGIF_UNKNOW = 0
MT_CONGIF_REQ = 1
MT_CONFIG_RESP = 2
ET_NONE = 0
ET_DES = 1
ET_AES = 2
ET_RSA = 3
CT_NONE = 0
CT_GZIP = 1
CT_DEFLATE = 2
LOG_PROTO_VERSION_UNKNOW = 0
LOG_PROTO_VERSION_CURRENT = 256



_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='com.bonree.one.logs.proto.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='com.bonree.one.logs.proto.Msg.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgLen', full_name='com.bonree.one.logs.proto.Msg.msgLen', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptType', full_name='com.bonree.one.logs.proto.Msg.encryptType', index=2,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compressType', full_name='com.bonree.one.logs.proto.Msg.compressType', index=3,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='com.bonree.one.logs.proto.Msg.timeStamp', index=4,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='com.bonree.one.logs.proto.Msg.msgType', index=5,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgBody', full_name='com.bonree.one.logs.proto.Msg.msgBody', index=6,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=236,
)

_MSG.fields_by_name['msgType'].enum_type = _MSGTYPE
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.enum_types_by_name['MsgType'] = _MSGTYPE
DESCRIPTOR.enum_types_by_name['EncryptType'] = _ENCRYPTTYPE
DESCRIPTOR.enum_types_by_name['CompressType'] = _COMPRESSTYPE
DESCRIPTOR.enum_types_by_name['LOG_MSG_VERSION'] = _LOG_MSG_VERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'bonree.proto.msg_pb2'
  # @@protoc_insertion_point(class_scope:com.bonree.one.logs.proto.Msg)
  })
_sym_db.RegisterMessage(Msg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
